name: love
version: 10.1
summary: LÖVE is an awesome framework you can use to make 2D games in Lua
description: 2D game development framework based on Lua and OpenGL
 LÖVE was created to be a user-friendly engine in which simple (or
 complicated) games could be made without having extensive knowledge
 of system or graphics functions and without having to dedicate time
 towards developing the same engine features time and time again.
 .
 Developed with cross-platform implementation in mind, it utilizes the
 latest open source libraries to deliver a similar game experience,
 independent of operating system. By relying on the Lua scripting language
 for game-specific programming, it allows even the novice game creator to
 quickly and efficiently develop an idea into a fully working game.

apps:
  run:
    command: launcher
    plugs: [network, network-bind, unity7, opengl]

parts:
  launcher:
    plugin: copy
    files:
      launcher: bin/launcher
  love:
    plugin: nil
    stage-packages:
      - libgl1-mesa-glx
      - libgl1-mesa-dri
      - liblove0
      - love
