name: vlc
version: 0.1
summary: vlc
description: vlc

apps:
  run:
    command: vlc
    plugs: [no-security]

plugs:
  no-security:
    interface: old-security
    security-template: unconfined

parts:
  vlc:
    plugin: x_vlcautotools
    source-type: git
    source: https://github.com/videolan/vlc.git
    build-packages:
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - binutils
      - bsdmainutils
      - build-essential
      - cpp
      - cpp-5
      - debhelper
      - dh-autoreconf
      - dh-buildinfo
      - dh-strip-nondeterminism
      - dpkg-dev
      - fontconfig
      - fontconfig-config
      - fonts-dejavu-core
      - g++
      - g++-5
      - gcc
      - gcc-5
      - gettext
      - gettext-base
      - gir1.2-atk-1.0
      - gir1.2-freedesktop
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-glib-2.0
      - gir1.2-gtk-2.0
      - gir1.2-notify-0.7
      - gir1.2-pango-1.0
      - gir1.2-rsvg-2.0
      - groff-base
      - icu-devtools
      - intltool-debian
      - liba52-0.7.4
      - liba52-0.7.4-dev
      - libaa1
      - libaa1-dev
      - libarchive-zip-perl
      - libasan2
      - libasn1-8-heimdal
      - libasound2
      - libasound2-data
      - libasound2-dev
      - libasprintf0v5
      - libass-dev
      - libass5
      - libasyncns0
      - libatk1.0-0
      - libatk1.0-data
      - libatk1.0-dev
      - libatomic1
      - libavahi-client-dev
      - libavahi-client3
      - libavahi-common-data
      - libavahi-common-dev
      - libavahi-common3
      - libavc1394-0
      - libavc1394-dev
      - libavcodec-dev
      - libavcodec-ffmpeg56
      - libavformat-dev
      - libavformat-ffmpeg56
      - libavutil-dev
      - libavutil-ffmpeg54
      - libbasicusageenvironment1
      - libbluray-dev
      - libbluray1
      - libboost-filesystem1.58.0
      - libboost-system1.58.0
      - libc-dev-bin
      - libc6-dev
      - libcaca-dev
      - libcaca0
      - libcairo-gobject2
      - libcairo-script-interpreter2
      - libcairo2
      - libcairo2-dev
      - libcc1-0
      - libcddb2
      - libcddb2-dev
      - libcdio-dev
      - libcdio13
      - libchromaprint-dev
      - libchromaprint0
      - libcilkrts5
      - libcroco3
      - libcrystalhd-dev
      - libcrystalhd3
      - libcups2
      - libdatrie1
      - libdbus-1-3
      - libdbus-1-dev
      - libdc1394-22
      - libdc1394-22-dev
      - libdca-dev
      - libdca0
      - libdirectfb-1.2-9
      - libdirectfb-dev
      - libdirectfb-extra
      - libdpkg-perl
      - libdrm-amdgpu1
      - libdrm-dev
      - libdrm-intel1
      - libdrm-nouveau2
      - libdrm-radeon1
      - libdrm2
      - libdvbpsi-dev
      - libdvbpsi10
      - libdvdnav-dev
      - libdvdnav4
      - libdvdread-dev
      - libdvdread4
      - libebml-dev
      - libebml4v5
      - libegl1-mesa
      - libegl1-mesa-dev
      - libelf1
      - libevdev2
      - libexpat1-dev
      - libfaad-dev
      - libfaad2
      - libfile-stripnondeterminism-perl
      - libflac-dev
      - libflac8
      - libfluidsynth-dev
      - libfluidsynth1
      - libfontconfig1
      - libfontconfig1-dev
      - libfreerdp-cache1.1
      - libfreerdp-client1.1
      - libfreerdp-codec1.1
      - libfreerdp-common1.1.0
      - libfreerdp-core1.1
      - libfreerdp-crypto1.1
      - libfreerdp-dev
      - libfreerdp-gdi1.1
      - libfreerdp-locale1.1
      - libfreerdp-primitives1.1
      - libfreerdp-rail1.1
      - libfreerdp-utils1.1
      - libfreetype6
      - libfreetype6-dev
      - libfribidi-dev
      - libgbm1
      - libgcc-5-dev
      - libgcrypt20-dev
      - libgdbm3
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-common
      - libgdk-pixbuf2.0-dev
      - libgirepository-1.0-1
      - libgl1-mesa-dev
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglapi-mesa
      - libgles1-mesa
      - libgles1-mesa-dev
      - libgles2-mesa
      - libgles2-mesa-dev
      - libglib2.0-0
      - libglib2.0-bin
      - libglib2.0-data
      - libglib2.0-dev
      - libglu1-mesa
      - libglu1-mesa-dev
      - libgme0
      - libgmpxxv4-4
      - libgnutls-dev
      - libgnutls28-dev
      - libgnutlsxx28
      - libgomp1
      - libgpg-error-dev
      - libgraphite2-3
      - libgroupsock8
      - libgsm1
      - libgssapi3-heimdal
      - libgtk2.0-0
      - libgtk2.0-common
      - libgtk2.0-dev
      - libgudev-1.0-0
      - libharfbuzz-dev
      - libharfbuzz-gobject0
      - libharfbuzz-icu0
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libice-dev
      - libice6
      - libicu-dev
      - libicu55
      - libidn11-dev
      - libinput10
      - libisl15
      - libiso9660-8
      - libiso9660-dev
      - libitm1
      - libjack-dev
      - libjack0
      - libjbig-dev
      - libjbig0
      - libjpeg-dev
      - libjpeg-turbo8
      - libjpeg-turbo8-dev
      - libjpeg8
      - libjpeg8-dev
      - libkate-dev
      - libkate1
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libldb1
      - liblircclient-dev
      - liblircclient0
      - liblivemedia-dev
      - liblivemedia50
      - libllvm3.8
      - liblsan0
      - liblua5.2-0
      - liblua5.2-dev
      - liblzma-dev
      - liblzo2-2
      - libmad0
      - libmad0-dev
      - libmatroska-dev
      - libmatroska6v5
      - libmirclient-dev
      - libmirclient9
      - libmircommon-dev
      - libmircommon5
      - libmircookie-dev
      - libmircookie2
      - libmirprotobuf3
      - libmodplug-dev
      - libmodplug1
      - libmp3lame0
      - libmpc3
      - libmpcdec-dev
      - libmpcdec6
      - libmpeg2-4
      - libmpeg2-4-dev
      - libmpfr4
      - libmpx0
      - libmtdev1
      - libmtp-common
      - libmtp-dev
      - libmtp9
      - libncurses5-dev
      - libncursesw5-dev
      - libnotify-dev
      - libnotify4
      - libnuma1
      - libogg-dev
      - libogg0
      - libomxil-bellagio-bin
      - libomxil-bellagio-dev
      - libomxil-bellagio0
      - libopenjpeg5
      - libopus-dev
      - libopus0
      - liborc-0.4-0
      - liborc-0.4-dev
      - libp11-kit-dev
      - libpango-1.0-0
      - libpango1.0-dev
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpangoxft-1.0-0
      - libpciaccess0
      - libpcre16-3
      - libpcre3-dev
      - libpcre32-3
      - libpcrecpp0v5
      - libperl5.22
      - libpipeline1
      - libpixman-1-0
      - libpixman-1-dev
      - libpng12-dev
      - libprotoc-dev
      - libpostproc-dev
      - libpostproc-ffmpeg53
      - libprotobuf-dev
      - libprotobuf-lite9v5
      - libprotobuf9v5
      - libproxy1v5
      - libpthread-stubs0-dev
      - libpulse-dev
      - libpulse-mainloop-glib0
      - libpulse0
      - libpython-stdlib
      - libpython2.7
      - libpython2.7-minimal
      - libpython2.7-stdlib
      - libqt5concurrent5
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5printsupport5
      - libqt5sql5
      - libqt5test5
      - libqt5widgets5
      - libqt5x11extras5
      - libqt5x11extras5-dev
      - libqt5xml5
      - libquadmath0
      - libraw1394-11
      - libraw1394-dev
      - libreadline-dev
      - libreadline6-dev
      - libresid-builder-dev
      - libresid-builder0c2a
      - libroken18-heimdal
      - librsvg2-2
      - librsvg2-common
      - librsvg2-dev
      - librtmp1
      - libsamplerate0
      - libsamplerate0-dev
      - libsasl2-2
      - libsasl2-modules-db
      - libschroedinger-1.0-0
      - libschroedinger-dev
      - libsdl-image1.2
      - libsdl-image1.2-dev
      - libsdl1.2-dev
      - libsdl1.2debian
      - libset-scalar-perl
      - libshine-dev
      - libshine3
      - libshout3
      - libshout3-dev
      - libsidplay2-dev
      - libsidplay2v5
      - libsigsegv2
      - libslang2-dev
      - libsm-dev
      - libsm6
      - libsmbclient
      - libsmbclient-dev
      - libsnappy1v5
      - libsndfile1
      - libsoxr0
      - libspeex-dev
      - libspeex1
      - libspeexdsp-dev
      - libspeexdsp1
      - libssh-gcrypt-4
      - libssh2-1
      - libssh2-1-dev
      - libstdc++-5-dev
      - libswresample-dev
      - libswresample-ffmpeg1
      - libswscale-dev
      - libswscale-ffmpeg3
      - libtag1-dev
      - libtag1v5
      - libtag1v5-vanilla
      - libtalloc2
      - libtasn1-6-dev
      - libtdb1
      - libtevent0
      - libthai-data
      - libthai0
      - libtheora-dev
      - libtheora0
      - libtiff5
      - libtiff5-dev
      - libtiffxx5
      - libtimedate-perl
      - libtinfo-dev
      - libtool
      - libtsan0
      - libtwolame-dev
      - libtwolame0
      - libubsan0
      - libudev-dev
      - libunistring0
      - libupnp-dev
      - libupnp6
      - libupnp6-dev
      - libusageenvironment3
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libv4l-0
      - libv4l-dev
      - libv4l2rds0
      - libv4lconvert0
      - libva-dev
      - libva-drm1
      - libva-egl1
      - libva-glx1
      - libva-tpi1
      - libva-wayland1
      - libva-x11-1
      - libva1
      - libvcdinfo-dev
      - libvcdinfo0
      - libvdpau-dev
      - libvdpau1
      - libvncclient1
      - libvncserver-config
      - libvncserver-dev
      - libvncserver1
      - libvorbis-dev
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libvpx3
      - libwacom-common
      - libwacom2
      - libwavpack1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-dev
      - libwayland-egl1-mesa
      - libwayland-server0
      - libwbclient0
      - libwebp-dev
      - libwebp5
      - libwebpdemux1
      - libwebpmux1
      - libwind0-heimdal
      - libwinpr-asn1-0.1
      - libwinpr-bcrypt0.1
      - libwinpr-credentials0.1
      - libwinpr-credui0.1
      - libwinpr-crt0.1
      - libwinpr-crypto0.1
      - libwinpr-dev
      - libwinpr-dsparse0.1
      - libwinpr-environment0.1
      - libwinpr-error0.1
      - libwinpr-file0.1
      - libwinpr-handle0.1
      - libwinpr-heap0.1
      - libwinpr-input0.1
      - libwinpr-interlocked0.1
      - libwinpr-io0.1
      - libwinpr-library0.1
      - libwinpr-path0.1
      - libwinpr-pipe0.1
      - libwinpr-pool0.1
      - libwinpr-registry0.1
      - libwinpr-rpc0.1
      - libwinpr-sspi0.1
      - libwinpr-sspicli0.1
      - libwinpr-synch0.1
      - libwinpr-sysinfo0.1
      - libwinpr-thread0.1
      - libwinpr-timezone0.1
      - libwinpr-utils0.1
      - libwinpr-winhttp0.1
      - libwinpr-winsock0.1
      - libx11-6
      - libx11-data
      - libx11-dev
      - libx11-xcb-dev
      - libx11-xcb1
      - libx264-148
      - libx264-dev
      - libx265-79
      - libx265-dev
      - libxau-dev
      - libxau6
      - libxcb-composite0
      - libxcb-composite0-dev
      - libxcb-dri2-0
      - libxcb-dri2-0-dev
      - libxcb-dri3-0
      - libxcb-dri3-dev
      - libxcb-glx0
      - libxcb-glx0-dev
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-keysyms1-dev
      - libxcb-present-dev
      - libxcb-present0
      - libxcb-randr0
      - libxcb-randr0-dev
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-render0-dev
      - libxcb-shape0
      - libxcb-shape0-dev
      - libxcb-shm0
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xfixes0-dev
      - libxcb-xkb1
      - libxcb-xv0
      - libxcb-xv0-dev
      - libxcb1
      - libxcb1-dev
      - libxcomposite-dev
      - libxcomposite1
      - libxcursor-dev
      - libxcursor1
      - libxdamage-dev
      - libxdamage1
      - libxdmcp-dev
      - libxdmcp6
      - libxext-dev
      - libxext6
      - libxfixes-dev
      - libxfixes3
      - libxfreerdp-client1.1
      - libxft-dev
      - libxft2
      - libxi-dev
      - libxi6
      - libxinerama-dev
      - libxinerama1
      - libxkbcommon-dev
      - libxkbcommon-x11-0
      - libxkbcommon0
      - libxkbfile1
      - libxml2
      - libxml2-dev
      - libxml2-utils
      - libxpm-dev
      - libxpm4
      - libxrandr-dev
      - libxrandr2
      - libxrender-dev
      - libxrender1
      - libxshmfence-dev
      - libxshmfence1
      - libxv1
      - libxvidcore4
      - libxxf86vm-dev
      - libxxf86vm1
      - libzvbi-common
      - libzvbi-dev
      - libzvbi0
      - linux-libc-dev
      - lua5.2
      - m4
      - make
      - man-db
      - mesa-common-dev
      - nettle-dev
      - patch
      - perl
      - perl-modules-5.22
      - pkg-config
      - po-debconf
      - python
      - python-minimal
      - python-talloc
      - python2.7
      - python2.7-minimal
      - qt5-qmake
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtchooser
      - samba-libs
      - shared-mime-info
      - uuid-dev
      - x11-common
      - x11proto-composite-dev
      - x11proto-core-dev
      - x11proto-damage-dev
      - x11proto-dri2-dev
      - x11proto-fixes-dev
      - x11proto-gl-dev
      - x11proto-input-dev
      - x11proto-kb-dev
      - x11proto-randr-dev
      - x11proto-render-dev
      - x11proto-xext-dev
      - x11proto-xf86vidmode-dev
      - x11proto-xinerama-dev
      - xorg-sgml-doctools
      - xtrans-dev
      - xz-utils
      - zlib1g-dev
      - zsh
      - zsh-common
