name: mame
version: "0.160"
summary: Multiple Arcade Machine Emulator (MAME)
description: MAME is a hardware emulator. it faithfully reproduces the behaviour of
 many arcade machines (it is not a simulation). This program is not a game
 but can directly, through ROM images, run the complete system of these old
 arcade machines. These ROMs are subject to copyright and it is in most of
 the cases illegal to use them if you do not own the arcade machine.
 .
 This package provides the MAME binary and configuration files.

apps:
  mame:
    command: launcher
    plugs: [X11, network, network-bind, unity7, opengl]

plugs:
  no-security:
    interface: old-security
    security-template: unconfined

parts:
  launcher:
    plugin: copy
    files:
      launcher: bin/launcher
      mame.ini: mame.ini
  mame:
    plugin: nil
    stage-packages:
      - mame
