name: minetest
version: 0.4.13
summary: Multiplayer infinite-world block sandbox
description: Minetest is a minecraft-inspired game written from scratch and licensed
 under the LGPL (version 2.1 or later). It supports both survival and
 creative modes along with multiplayer support, dynamic lighting, and an
 "infinite" map generator.

apps:
  run:
    command: launcher
    plugs: [no-security]

plugs:
  no-security:
    interface: old-security
    security-template: unconfined

parts:
  launcher:
    plugin: copy
    files:
      launcher: bin/launcher
  minetest:
    plugin: nil
    stage-packages:
      - libgl1-mesa-glx
      - libgl1-mesa-dri
      - minetest
