name: minetest
version: 0.4.13
summary: Multiplayer infinite-world block sandbox
description: Minetest is a minecraft-inspired game written from scratch and licensed
 under the LGPL (version 2.1 or later). It supports both survival and
 creative modes along with multiplayer support, dynamic lighting, and an
 "infinite" map generator.

apps:
  run:
    command: minetest
    plugs: [x11]

parts:
  launcher:
    plugin: copy
    files:
      minetest: bin/minetest
  minetest:
    plugin: nil
    stage-packages:
      - libgl1-mesa-glx
      - libgl1-mesa-dri
      - minetest
