name: netflix
version: 0.1
summary: Netflix
description: Netflix

apps:
  run:
    command: bin/netflix-launcher
    plugs: [no-security]

plugs:
  no-security:
    interface: old-security
    security-template: unconfined

parts:
  launcher:
    plugin: copy
    files: 
      netflix-launcher: bin/netflix-launcher
  netflix:
    plugin: nil
    stage-packages:
      - google-chrome-stable
      - libexif12
      - libgl1-mesa-glx
      - libgl1-mesa-dri
      - libcanberra-gtk-module
