#################################################
##                                             ##
## ffmpeg - Snapcraft.yaml                     ##
##                                             ##
#################################################
##                                             ##
## 2016-05-06 : Adding some precision about    ##
##              the lack of confinement for    ##
##              this snap in description field.##
##              Removing the ffmpeg parts and  ##
##              re-use the one added on the    ##
##              Snappy/Parts page on           ##
##              wiki.uubuntu.com               ##
##                                             ##
#################################################

name: ffmpeg
version: 4.01~git
summary: Tools for transcoding, streaming and playing of multimedia files
description: FFmpeg is the leading multimedia framework, able to decode, encode, transcode,
 mux, demux, stream, filter and play pretty much anything that humans and
 machines have created. It supports the most obscure ancient formats up to the
 cutting edge.
 Due to the lack of interfaces for medias, this snap is currently unconfined
 This package contains;
  ffmpeg - a command line tool to convert multimedia files between formats
  ffserver - a multimedia streaming server for live broadcasts
  ffplay - a simple media player based on SDL and the FFmpeg libraries
  ffprobe - a simple multimedia stream analyzer
  qt-faststart - a utility to rearrange Quicktime files

# ffcfstress     ffmpeg         ffmpeg2theora  ffmvforce      ffplay         ffprobe        ffserver       ffset          fftest

apps:
  ffmpeg:
    command: ffmpeg.launcher
    plugs: [no-security]
  ffplay:
    command: ffplay.launcher
    plugs: [no-security]
  ffprobe:
    command: ffprobe.launcher
    plugs: [no-security]
  ffserver:
    command: ffserver.launcher
    plugs: [no-security]

plugs:
  no-security:
    interface: old-security
    security-template: unconfined

parts:

  # 2016-05-06: [Winael] Removing the ffmpeg parts and re-use the one added on the Snappy/Parts page on wiki.uubuntu.com

  launcher:
    after:
      - ffmpeg
    plugin: copy
    files:
      ffmpeg.launcher: ffmpeg.launcher
      ffplay.launcher: ffplay.launcher
      ffprobe.launcher: ffprobe.launcher
      ffserver.launcher: ffserver.launcher

  
